/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicebatch45days2026;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class PracticeScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PracticeScreen.class.getName());

    /**
     * Creates new form PracticeScreen
     */
    public PracticeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        navHome = new javax.swing.JPanel();
        navHomeText = new javax.swing.JLabel();
        navContact = new javax.swing.JPanel();
        navContactText = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        dashboardAllScreen = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 51, 0));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to Dashbaord Sreen");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(298, 298, 298))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navHomeMouseExited(evt);
            }
        });

        navHomeText.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        navHomeText.setText("Home");

        javax.swing.GroupLayout navHomeLayout = new javax.swing.GroupLayout(navHome);
        navHome.setLayout(navHomeLayout);
        navHomeLayout.setHorizontalGroup(
            navHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navHomeLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(navHomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        navHomeLayout.setVerticalGroup(
            navHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navHomeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(navHomeText)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.add(navHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, 60));

        navContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navContactMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navContactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navContactMouseExited(evt);
            }
        });

        navContactText.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        navContactText.setText("Contact Us");

        javax.swing.GroupLayout navContactLayout = new javax.swing.GroupLayout(navContact);
        navContact.setLayout(navContactLayout);
        navContactLayout.setHorizontalGroup(
            navContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navContactLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(navContactText)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        navContactLayout.setVerticalGroup(
            navContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navContactLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(navContactText)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.add(navContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel4.setText("Rate us");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel4)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 610));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        dashboardAllScreen.setBackground(new java.awt.Color(255, 255, 255));
        dashboardAllScreen.setOpaque(false);

        javax.swing.GroupLayout dashboardAllScreenLayout = new javax.swing.GroupLayout(dashboardAllScreen);
        dashboardAllScreen.setLayout(dashboardAllScreenLayout);
        dashboardAllScreenLayout.setHorizontalGroup(
            dashboardAllScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        dashboardAllScreenLayout.setVerticalGroup(
            dashboardAllScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jPanel1.add(dashboardAllScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 860, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navHomeMouseEntered
        // TODO add your handling code here:
        Color obj = new Color(204,51,0);
        navHome.setBackground(obj);
        navHomeText.setForeground(Color.white);
        
    }//GEN-LAST:event_navHomeMouseEntered

    private void navHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navHomeMouseExited
        // TODO add your handling code here:
        
        Color obj = new Color(242,242,242);
        navHome.setBackground(obj);
        navHomeText.setForeground(Color.black);
        
    }//GEN-LAST:event_navHomeMouseExited

    private void navContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navContactMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_navContactMouseClicked

    private void navContactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navContactMouseEntered
        // TODO add your handling code here:
          Color obj = new Color(204,51,0);
        navContact.setBackground(obj);
        navContactText.setForeground(Color.white);
    }//GEN-LAST:event_navContactMouseEntered

    private void navContactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navContactMouseExited
        // TODO add your handling code here:
          Color obj = new Color(242,242,242);
        navContact.setBackground(obj);
        navContactText.setForeground(Color.black);
    }//GEN-LAST:event_navContactMouseExited

    private void navHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navHomeMouseClicked
        // TODO add your handling code here:
        HomeScreen obj = new HomeScreen();
        
        dashboardAllScreen.removeAll();
        dashboardAllScreen.setLayout(new BorderLayout());
        dashboardAllScreen.add(obj,BorderLayout.CENTER);
        dashboardAllScreen.revalidate();
        dashboardAllScreen.repaint();
       
    }//GEN-LAST:event_navHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PracticeScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashboardAllScreen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel navContact;
    private javax.swing.JLabel navContactText;
    private javax.swing.JPanel navHome;
    private javax.swing.JLabel navHomeText;
    // End of variables declaration//GEN-END:variables
}
